services:
  rpid:
    build: .
    image: parmaster/rpid:main
    container_name: rpid
    hostname: pi4.local
    privileged: true
    ports:
      - "8095:8095"
    volumes:
      - /sys/class/thermal/thermal_zone0:/sys/class/thermal/thermal_zone0:ro
      - /dev/gpiomem:/dev/gpiomem
      - /sys:/sys
      - /sys/devices/system/cpu/cpu0/cpufreq/stats:/sys/devices/system/cpu/cpu0/cpufreq/stats:ro
    devices:
      - /dev/i2c-4:/dev/i2c-4
