server:
  listen: :8095
  dbg: false
storage:
  type: sqlite
  path: /etc/rpid/data.db
fan:
  tachPin: GPIO15
  controlPin: GPIO18
  high: 45
  low: 40
modules:
  i2c: 4
  bmp280:
    enabled: true
    addr: 0x76
  htu21:
    enabled: true
    addr: 0x40
  system:
    enabled: true
