server:
  listen: :8095
  dbg: false
storage:
  type: sqlite
  path: file:/etc/rpid/data.db?mode=rwc&_journal_mode=WAL
  readOnly: false
fan:
  tachPin: GPIO15
  controlPin: GPIO18
  high: 48 # 45C is optimal for winter, 48 is OK for summer to avoid frequent FAN activations
  low: 40
modules:
  i2c: 4
  bmp280:
    enabled: true
    addr: 0x76
  htu21:
    enabled: true
    addr: 0x40
  system:
    enabled: true
